# FROM ubuntu:18.04
FROM nvidia/cuda

# change this based on your location
ENV TZ=America/Los_Angeles
ENV DEBIAN_FRONTEND noninteractive
COPY ./webots_2018a-rev2_amd64_p.deb ./webots/
RUN apt-get update &&  \
apt-get install libnss3-dev -y && \
apt-get install gdebi -y && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
gdebi --option=APT::Get::force-yes=1,APT::Get::Assume-Yes=1 -n ./webots/webots_2018a-rev2_amd64_p.deb

CMD bash