"""

This scripts load the texture generated by the `/estimators/inference.py` file, where each pixel in the texture is > 1 if the
patch in that point is traversable, and apply it to the ground map in blender in order to create a good looking visualisation.

### Usage

Edit the global variable `MAP_PATH` and `TEXT_PATH`, then

```
blender ./traversability.blend --python heigtmap.py
```

"""
import bpy
import cv2


MAP_PATH = '/home/francesco/Documents/Master-Thesis/core/maps/test/querry-big-10.png'
TEXT_PATH = '/home/francesco/Desktop/textures/querry-None.png'
#
# MAP_PATH = '/home/francesco/Documents/Master-Thesis/core/maps/train/bars1.png'
# TEXT_PATH = '/home/francesco/Desktop/textures/bars1-None.png'

MAP_NAME = 'querry-big-10.png'
MAP_KEY = 'Grid'
TEX_NAME = 'traversability-texture'

map = bpy.data.objects[MAP_KEY]
image = cv2.imread(MAP_PATH)
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

if image.dtype == 'uint8':
    image = image / 256.
if image.dtype == 'uint16':
    image = image / 65536.
if image.dtype == 'uint32':
    image = image / 4294967296.


nodes = bpy.data.materials['traversability'].node_tree.nodes
nodes.get('Image Texture').image = bpy.data.images.load(TEXT_PATH)

map_texture = bpy.data.textures.get('map')
map_texture.image = bpy.data.images.load(MAP_PATH)
