"""

This scripts load the texture generated by the `/estimators/inference.py` file, where each pixel in the texture is > 1 if the
patch in that point is traversable, and apply it to the ground map in blender in order to create a good looking visualisation.

### Usage

Edit the global variable `MAP_PATH` and `TEXT_PATH`, then

```
blender ./quarry.blend --python render_hm.py
```

"""
import cv2
import numpy as np


class BlenderVisualization():

    def draw_heightmap(self, map_path):
        map_texture = bpy.data.textures.get('map')
        map_texture.image = bpy.data.images.load(map_path)

    def setup_camera(self):
        cam = bpy.data.objects['Camera']
        # cam.rotation_mode = ''
        # cam.location = [5.50149, -3.50377, 4.48249]
        # cam.rotation_euler = [np.pi / 4, 0, np.pi / 4]

        bpy.data.scenes['Scene'].camera = cam

        camera = bpy.data.cameras['Camera']

        # camera.lens_unit = 'FOV'
        # camera.angle = 1.74

    def render(self, file_path):
        scene = bpy.context.scene
        scene.cycles.samples = 32
        # scene.render.resolution_x = 2140
        # scene.render.resolution_y = 2140

        bpy.context.scene.render.filepath = file_path
        bpy.ops.render.render(use_viewport=True, write_still=True)


    def __call__(self, map_path, file_path):
        self.draw_heightmap(map_path)
        self.setup_camera()
        self.render(file_path)

    @staticmethod
    def run_from_python():
        """
        This can be used in any others python code, it will create a new process
        to run the script in blender and display the rendered image.
        :return:
        """
        import subprocess
        import matplotlib.pyplot as plt
        from os import path

        base_dir, _ = path.split(__file__)

        subprocess.run(["blender", '{}/traversability.blend'.format(base_dir), '--python', '{}/heightmap.py'.format(base_dir)])

        rendered = cv2.imread(FILE_PATH)
        rendered = cv2.cvtColor(rendered, cv2.COLOR_BGR2RGB)

        plt.imshow(rendered)
        plt.show()

if __name__ == '__main__':
    import bpy
    import glob
    from os import path

    MAP_PATH = '/home/francesco/Documents/Master-Thesis/core/maps/train/steps1.png'

    OUT_DIR = '/home/francesco/Desktop/'
    b_vis = BlenderVisualization()
    name = path.splitext(path.basename(MAP_PATH))[0]
    print(name)
    b_vis(MAP_PATH, '{}/{}.png'.format(OUT_DIR, name))

    # bpy.ops.wm.quit_blender()




